FROM rust:1.92-bookworm AS builder
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY crates ./crates
COPY services ./services
COPY migrations ./migrations
RUN cargo build -p gittree-coordinator --release \
    && cargo build -p gittree-git-hook --bin gittree-pre-receive --bin gittree-post-receive --release

FROM debian:bookworm-slim
RUN useradd -m -u 10001 gittree
COPY --from=builder /app/target/release/gittree-coordinator /usr/local/bin/gittree-coordinator
COPY --from=builder /app/target/release/gittree-pre-receive /usr/local/bin/gittree-pre-receive
COPY --from=builder /app/target/release/gittree-post-receive /usr/local/bin/gittree-post-receive
USER gittree
ENTRYPOINT ["/usr/local/bin/gittree-coordinator"]
